#!/bin/bash
#
# agency-scan.sh
# Scans project directories and generates a dynamic registry.
# Detects projects by the presence of .git, package.json, CONTEXT.md, etc.
#
# Usage: agency scan

set -euo pipefail

# Source env
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/env.sh"

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
DIM='\033[2m'
NC='\033[0m'

REGISTRY="$AGENCY_DIR/projects.yaml"

# Parse colon-separated AGENCY_PROJECTS_DIR into array
IFS=':' read -ra SCAN_DIRS <<< "$AGENCY_PROJECTS_DIR"

# Detect project type
detect_stack() {
  local dir=$1
  local stack=""

  [[ -f "$dir/package.json" ]] && {
    grep -q '"expo"' "$dir/package.json" 2>/dev/null && stack="expo,react-native"
    grep -q '"next"' "$dir/package.json" 2>/dev/null && stack="nextjs"
    grep -q '"react"' "$dir/package.json" 2>/dev/null && [[ -z "$stack" ]] && stack="react"
    grep -q '"vue"' "$dir/package.json" 2>/dev/null && stack="vue"
    grep -q '"svelte"' "$dir/package.json" 2>/dev/null && stack="svelte"
    [[ -z "$stack" ]] && stack="node"
  }
  [[ -f "$dir/requirements.txt" || -f "$dir/pyproject.toml" ]] && stack="${stack:+$stack,}python"
  [[ -f "$dir/Cargo.toml" ]] && stack="${stack:+$stack,}rust"
  [[ -f "$dir/go.mod" ]] && stack="${stack:+$stack,}go"
  [[ -f "$dir/pnpm-workspace.yaml" ]] && stack="${stack:+$stack,}monorepo-pnpm"
  [[ -f "$dir/turbo.json" ]] && stack="${stack:+$stack,}turborepo"

  echo "${stack:-unknown}"
}

detect_package_manager() {
  local dir=$1
  [[ -f "$dir/pnpm-lock.yaml" ]] && echo "pnpm" && return
  [[ -f "$dir/bun.lockb" || -f "$dir/bun.lock" ]] && echo "bun" && return
  [[ -f "$dir/yarn.lock" ]] && echo "yarn" && return
  [[ -f "$dir/package-lock.json" ]] && echo "npm" && return
  echo "none"
}

has_context() {
  local dir=$1
  [[ -f "$dir/CONTEXT.md" || -f "$dir/claude.md" || -f "$dir/CLAUDE.md" ]] && echo "true" || echo "false"
}

echo ""
echo -e "${GREEN}Agency OS — Project Scan${NC}"
echo ""

# Start YAML
cat > "$REGISTRY" << HEADER
# Agency OS — Project Registry
# Auto-generated by agency-scan
# Last scan: $(date '+%Y-%m-%d %H:%M')

projects:
HEADER

project_count=0
placeholder_count=0

for scan_dir in "${SCAN_DIRS[@]}"; do
  # Expand ~ if present
  scan_dir="${scan_dir/#\~/$HOME}"

  if [[ ! -d "$scan_dir" ]]; then
    echo -e "${YELLOW}  Directory not found: $scan_dir${NC}"
    continue
  fi

  echo -e "${BLUE}Scanning $scan_dir...${NC}"

  for project_dir in "$scan_dir"/*/; do
    [[ ! -d "$project_dir" ]] && continue

    name=$(basename "$project_dir")

    # Skip hidden dirs
    [[ "$name" == .* ]] && continue

    has_git=false
    [[ -d "$project_dir/.git" || -f "$project_dir/.git" ]] && has_git=true
    has_pkg=false
    [[ -f "$project_dir/package.json" || -f "$project_dir/pyproject.toml" || -f "$project_dir/Cargo.toml" || -f "$project_dir/go.mod" ]] && has_pkg=true

    path="${project_dir%/}"

    if [[ "$has_git" == false && "$has_pkg" == false ]]; then
      cat >> "$REGISTRY" << PLACEHOLDER
  - name: "$name"
    path: "$path"
    stack: "empty"
    package_manager: "none"
    has_context: false
    placeholder: true
PLACEHOLDER
      echo -e "   $name ${DIM}[placeholder]${NC}"
      ((placeholder_count++)) || true
      continue
    fi

    stack=$(detect_stack "$path")
    pkg_manager=$(detect_package_manager "$path")
    has_ctx=$(has_context "$path")

    cat >> "$REGISTRY" << PROJECT
  - name: "$name"
    path: "$path"
    stack: "$stack"
    package_manager: "$pkg_manager"
    has_context: $has_ctx
PROJECT

    status_icon="+"
    [[ "$has_ctx" == "false" ]] && status_icon="?"

    echo -e "   $status_icon ${name} ${DIM}[$stack]${NC}"
    ((project_count++)) || true
  done
done

echo ""
echo -e "${GREEN}$project_count projects + $placeholder_count placeholders -> $REGISTRY${NC}"

# Warn about projects without CONTEXT.md
if command -v yq &>/dev/null; then
  missing_ctx=$(yq '.projects[] | select(.has_context == false) | .name' "$REGISTRY" 2>/dev/null)
  if [[ -n "$missing_ctx" ]]; then
    echo ""
    echo -e "${YELLOW}Projects without CONTEXT.md (agents work better with it):${NC}"
    echo "$missing_ctx" | sed 's/^/   - /'
  fi
fi

echo ""
